name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}

    steps:
    - name: GitHub Action for Zeit
      uses: actions/zeit-now@1.0.0

    - name: deploy
      run: |
        now --token ${ZEIT_TOKEN} -A ./now.json
