name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: GitHub Action for Zeit
      uses: actions/zeit-now@1.0.0
   
    - name: deploy
      env:
        TOKEN: ${{ ZEIT_TOKNE }}
      run: |
        now --token ${TOKEN}
