name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: GitHub Action for Zeit
      uses: actions/zeit-now@1.0.0
   
    - name: deploy
      env:
        TOKEN: ${{ secrets.ZEIT_TOKEN }}
      run: |
        now --token ${TOKEN}
